config/routes.rb
FootballManagementSystem::Application.routes.draw do
  resources :contacts

  resources :static_pages
  resources :competitions
  resources :fixtures
  resources :players
  resources :teams
  resources :news_items

  match 'tables/all/edit' => 'tables#edit_multiple', as: :edit_all_tables, via: :get
  match 'tables/all' => 'tables#update_multiple', as: :update_all_tables, via: :post
  match 'tables/all' => 'tables#destroy_multiple', as: :destroy_all_tables, via: :delete

  resources :tables

  root 'news_items#index'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
	validates :name, :body, presence: true
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.order(:name)
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @static_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.require(:static_page).permit(:name, :body)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @static_page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <fieldset>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: "form-control wysihtml5" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-success btn-sm" %>
    </div>
  </fieldset>
<% end %>

app/views/static_pages/edit.html.erb
<% content_for :title, "Editing Page" %>

<%= render 'form' %>

<%= link_to 'Show', @static_page, class: "btn btn-xs btn-success" %> |
<%= link_to 'Back', static_pages_path, class: "btn btn-xs btn-primary" %>

app/views/static_pages/index.html.erb
<% content_for :title, "Static Pages" %>

<div class="center"><%= link_to 'New Static page', new_static_page_path, class: "btn btn-primary btn-sm" %></div><br />

<table class="table table-striped table-hover">
  <thead>
    <tr class="warning">
      <th>Name</th>
      <th>Body</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr class="<%= cycle('info', 'success') %>">
        <td><%= static_page.name %></td>
        <td><%= truncate(strip_tags(static_page.body), length: 60) %></td>
        <td style="text-align: right;"><%= link_to 'Show', static_page, class: "btn btn-success btn-xs" %>
          <%= link_to 'Edit', edit_static_page_path(static_page), class: "btn btn-warning btn-xs" %>
          <%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/static_pages/new.html.erb
<% content_for :title, "Adding Page" %>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path, class: "btn btn-primary btn-xs" %>

app/views/static_pages/show.html.erb
<% content_for :title, @static_page.name %>

<p>
  <%= @static_page.body.html_safe %>
</p>

<%= link_to 'Edit', edit_static_page_path(@static_page), class: "btn btn-warning btn-xs"  %> |
<%= link_to 'Back', static_pages_path, class: "btn btn-primary btn-xs" %>