config/routes.rb
FootballManagementSystem::Application.routes.draw do
  resources :contacts

  resources :static_pages
  resources :competitions
  resources :fixtures
  resources :players
  resources :teams
  resources :news_items

  match 'tables/all/edit' => 'tables#edit_multiple', as: :edit_all_tables, via: :get
  match 'tables/all' => 'tables#update_multiple', as: :update_all_tables, via: :post
  match 'tables/all' => 'tables#destroy_multiple', as: :destroy_all_tables, via: :delete

  resources :tables

  root 'news_items#index'

end

app/models/competition.rb
class Competition < ActiveRecord::Base
	has_many :fixtures

	validates :name, presence: true
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @competition }
      else
        format.html { render action: 'new' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :is_league)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @competition.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <fieldset>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :is_league %><br>
      <%= f.check_box :is_league, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-success btn-sm" %>
    </div>
</fieldset>
<% end %>

app/views/competitions/edit.html.erb
<% content_for :title, "Editing Competition" %>

<%= render 'form' %>

<%= link_to 'Show', @competition, class: "btn btn-xs btn-success" %> |
<%= link_to 'Back', competitions_path, class: "btn btn-xs btn-primary" %>

app/views/competitions/index.html.erb
<% content_for :title, "Competitions" %>

<div class="center"><%= link_to 'New Competition', new_competition_path, class: "btn btn-primary btn-sm" %></div><br />

<table class="table table-striped table-hover">
  <thead>
    <tr class="warning">
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr class="<%= cycle('info', 'success') %>">
        <td><%= competition.name %></td>
        <td><%= "<span class='label label-success'>League</span>".html_safe if competition.is_league %><%= "<span class='label label-danger'>Cup/Other</span>".html_safe unless competition.is_league %></td>
        <td style="text-align: right;"><%= link_to 'Show', competition, class: "btn btn-success btn-xs" %>
          <%= link_to 'Edit', edit_competition_path(competition), class: "btn btn-warning btn-xs" %>
        <%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/competitions/new.html.erb
<% content_for :title, "Adding Competition" %>

<%= render 'form' %>

<%= link_to 'Back', competitions_path, class: "btn btn-primary btn-xs" %>

app/views/competitions/show.html.erb
<% content_for :title, @competition.name %>
<p>
  <strong>Is league:</strong>
  <%= @competition.is_league %>
</p>

<%= link_to 'Edit', edit_competition_path(@competition), class: "btn btn-warning btn-xs" %> |
<%= link_to 'Back', competitions_path, class: "btn btn-primary btn-xs" %>