config/routes.rb
FootballManagementSystem::Application.routes.draw do
  resources :contacts

  resources :static_pages
  resources :competitions
  resources :fixtures
  resources :players
  resources :teams
  resources :news_items

  match 'tables/all/edit' => 'tables#edit_multiple', as: :edit_all_tables, via: :get
  match 'tables/all' => 'tables#update_multiple', as: :update_all_tables, via: :post
  match 'tables/all' => 'tables#destroy_multiple', as: :destroy_all_tables, via: :delete

  resources :tables

  root 'news_items#index'

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  include TablesHelper
  before_action :set_table, only: [:show, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = get_table_sorted
  end

  # GET /tables/new
  def new
    if Table.first == nil
      generate_base_table
      redirect_to tables_path, notice: 'Table data successfully created!'
    else
      redirect_to tables_path, notice: 'Table data already exists!'
    end
  end

  def edit_multiple
    @tables = get_table_sorted
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @table }
      else
        format.html { render action: 'new' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_multiple
    params["table"].keys.each do |id|
      @table = Table.find(id.to_i)
      @table.update_attributes(table_params(id))
    end
    redirect_to tables_path, notice: 'Table was successfully updated.'
  end

  # DELETE /tables/all
  def destroy_multiple
    wipe_base_table
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table data has been cleared.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params(id)
      params.require(:table).fetch(id).permit(:team_id, :played, :won, :drawn, :lost, :for, :against, :deducted)
    end

    def get_table_sorted
      @tables = Table.all
      @tables = @tables.sort_by { |x| [x.points, x.goal_difference, x.for] }
      @tables = @tables.reverse
    end
end

app/helpers/tables_helper.rb
module TablesHelper
	def generate_base_table
  	teams = Team.where in_league: true
  	teams.each do |team|
  		Table.create team_id: team.id, played: 0, won: 0, drawn: 0, lost: 0, for: 0, against: 0, deducted: 0
  	end
  end

  def wipe_base_table
  	Table.destroy_all
  end
end

app/views/tables/_form.html.erb
<%= form_for :table, :url => { action: 'update_multiple' } do %>

  <table class="table table-striped table-hover">
  <thead>
    <tr class="warning">
      <th>Team</th>
      <th class="center">P</th>
      <th class="center">W</th>
      <th class="center">D</th>
      <th class="center">L</th>
      <th class="center">F</th>
      <th class="center">A</th>
      <th class="center">Deducted</th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr class="<%= cycle('info', 'success') -%>">
        <%= fields_for "table[]", table do |f| %>
          <td><%= table.team.long_name %></td>
          <td><%= f.text_field :played, class: "form-control center" %></td>
          <td><%= f.text_field :won, class: "form-control center" %></td>
          <td><%= f.text_field :drawn, class: "form-control center" %></td>
          <td><%= f.text_field :lost, class: "form-control center" %></td>
          <td><%= f.text_field :for, class: "form-control center" %></td>
          <td><%= f.text_field :against, class: "form-control center" %></td>
          <td><%= f.text_field :deducted, class: "form-control center" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Save changes", class: "btn btn-sm btn-success" %>
<% end %>

app/views/tables/edit.html.erb
<% content_for :title, "Editing table" %>

<%= render 'form' %>

app/views/tables/edit_multiple.erb
<% content_for :title, "Editing table" %>

<%= render 'form' %>

<div style="margin-top: 100px;" class="center"><hr /><%= link_to 'Wipe all table data', destroy_all_tables_path, method: :delete, data: { confirm: 'This cannot be reversed. Are you sure?' }, class: "btn btn-danger btn-xs" %></div>

app/views/tables/index.html.erb
<% content_for :title, "Table" %>

<% if @tables[0] == nil %>
<div class="center"><p>There is no table data yet, please click here to generate the base data.</p><%= link_to 'New Table', new_table_path, class: "btn btn-primary btn-sm" %></div><br />
<% end %>

<% unless @tables[0] == nil %>
<table class="table table-striped table-hover">
  <thead>
    <tr class="warning">
      <th>Pos.</th>
      <th>Team</th>
      <th>P</th>
      <th>W</th>
      <th>D</th>
      <th>L</th>
      <th>F</th>
      <th>A</th>
      <th>GD</th>
      <th>Pts</th>
      <th>Deducted</th>
    </tr>
  </thead>

  <tbody>
    <% i = 1 %>
    <% @tables.each do |table| %>
      <tr class="<%= cycle('info', 'success') -%>">
        <td><%= i.to_s + "." %></td>
        <td><%= table.team.long_name %></td>
        <td><%= table.played %></td>
        <td><%= table.won %></td>
        <td><%= table.drawn %></td>
        <td><%= table.lost %></td>
        <td><%= table.for %></td>
        <td><%= table.against %></td>
        <td><%= table.goal_difference %></td>
        <td><%= table.points %></td>
        <td><%= table.deducted if table.deducted > 0 %></td>
      </tr>
      <% i += 1 %>
    <% end %>
  </tbody>
</table>
<%= link_to 'Edit Table', edit_all_tables_path, class: "btn btn-sm btn-warning" %>
<% end %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @table.team %>
</p>

<p>
  <strong>Played:</strong>
  <%= @table.played %>
</p>

<p>
  <strong>Won:</strong>
  <%= @table.won %>
</p>

<p>
  <strong>Drawn:</strong>
  <%= @table.drawn %>
</p>

<p>
  <strong>Lost:</strong>
  <%= @table.lost %>
</p>

<p>
  <strong>For:</strong>
  <%= @table.for %>
</p>

<p>
  <strong>Against:</strong>
  <%= @table.against %>
</p>

<p>
  <strong>Deducted:</strong>
  <%= @table.deducted %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>