config/routes.rb
FootballManagementSystem::Application.routes.draw do
  resources :contacts

  resources :static_pages
  resources :competitions
  resources :fixtures
  resources :players
  resources :teams
  resources :news_items

  match 'tables/all/edit' => 'tables#edit_multiple', as: :edit_all_tables, via: :get
  match 'tables/all' => 'tables#update_multiple', as: :update_all_tables, via: :post
  match 'tables/all' => 'tables#destroy_multiple', as: :destroy_all_tables, via: :delete

  resources :tables

  root 'news_items#index'

end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html lang="en">
  <head>
      <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
      <meta charset="utf-8">
      <title>FMS</title>
      
      <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		  <%= csrf_meta_tags %>
  </head>
    
  <body>
  	<div class="navbar navbar-fixed-top navbar-inverse">
  		<div class="container">
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="<%= root_url %>">FMS</a>
			  </div>
			  <div class="navbar-collapse collapse navbar-responsive-collapse">
			    <ul class="nav navbar-nav">
			      <li><a href="<%= root_url %>">Home</a></li>
			      <li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stats <b class="caret"></b></a>
			        <ul class="dropdown-menu">
			          <li><%= link_to "Fixtures & Results", fixtures_path %></li>
			          <li><%= link_to "Squad & Stats", players_path %></li>
			          <li><%= link_to "League Table", tables_path %></li>
			        </ul>
			      </li>
			      <li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Club Info <b class="caret"></b></a>
			        <ul class="dropdown-menu">
			        	<% @menu_items.each do |menu_item| %>
				          <li><%= link_to menu_item.name, menu_item %></li>
			          <% end %>
			          <li class="divider"></li>
			          <li><%= link_to "Contact Us", contacts_path %></li>
			        </ul>
			      </li>
			      <li><a href="#">Forum</a></li>
			      <li><a href="#">Gallery</a></li>
			    </ul>
			    <form class="navbar-form navbar-right">
			      <input type="text" class="form-control col-lg-8" placeholder="Search">
			    </form>
			  </div>
			</div>
		</div>
  
		<!-- HEADER 
		=================================-->
		<div class="jumbotron text-center">
	    <div class="container">
	      <div class="row">
	        <div class="col-md-12">
	          <h1>Football Management System</h1>
	          <p>Welcome to the Open Source Ruby on Rails project built around a standard Bootstrap theme. Thank you for your interest. Please 
	          feel free to pull the project from GitHub and help out.</p>        
	        </div>
	      </div>
	    </div> 
		</div>
		<!-- /header container-->

		<!-- CONTENT
		=================================-->
		<div class="container">
			
			<% if notice %>
			<div class="row">
				<div class="col-md-12">
					<div class="alert alert-dismissable alert-success">
					  <button type="button" class="close" data-dismiss="alert">×</button>
					  <%= notice %>
					</div>
				</div>
			</div>
			<% end %>

	    <div class="row">
        <div class="col-md-8">
        	<div class="panel panel-info">
					  <div class="panel-heading">
					    <h3 class="panel-title"><%= yield(:title) %></h3>
					  </div>
					  <div class="panel-body">
					    <%= yield %>
					  </div>
					</div>
        </div>

        <div class="col-md-4">
        	<div class="panel panel-info">
					  <div class="panel-heading">
					    <h3 class="panel-title">Panel primary</h3>
					  </div>
					  <div class="panel-body">
					    Side bar
					  </div>
					</div>
        </div>
	    </div>

	    <hr />
	    <div id="footer">Copyright &copy; <%= Time.now.year %> <%= link_to "Hightowersoft", "http://www.hightowersoft.co.uk" %> | Released under the <%= link_to "MIT License", "http://opensource.org/licenses/MIT" %></div>
		</div>
		<!-- /CONTENT ============-->        
	</body>
</html>